check

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -7,12 +7,6 @@ on:
   pull_request:
     branches:
       - main
-      - name: Verify kubeconfig
-      run: |
-        if ! kubectl config view; then
-          echo "Error: kubeconfig is not valid"
-          exit 1
-        fi
 
 jobs:
   build:
@@ -42,25 +36,34 @@ jobs:
       - name: Push Docker image
         run: docker push badshanoordeen/just-try:latest
 
-  # deploy:
-  #   runs-on: ubuntu-latest
-  #   needs: build
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
 
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v2
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-  #     - name: Set up kubectl
-  #       uses: azure/setup-kubectl@v1
-  #       with:
-  #         version: "v1.21.0"
+      - name: Set up kubectl
+        uses: azure/setup-kubectl@v1
+        with:
+          version: "v1.21.0"
 
-  #     - name: Update Kubernetes deployment
-  #       run: kubectl set image deployment/just-try-deployment just-try=badshanoordeen/just-try:${{ github.sha }}
-  #       env:
-  #         KUBECONFIG: ${{ secrets.KUBECONFIG }}
+      - name: Verify kubeconfig
+        run: |
+          if ! kubectl config view; then
+            echo "Error: kubeconfig is not valid"
+            exit 1
+          fi
+        env:
+          KUBECONFIG: ${{ secrets.KUBECONFIG }}
 
-  #     - name: Rollout restart
-  #       run: kubectl rollout restart deployment/just-try-deployment
-  #       env:
-  #         KUBECONFIG: ${{ secrets.KUBECONFIG }}
+      - name: Update Kubernetes deployment
+        run: kubectl set image deployment/just-try-deployment just-try=badshanoordeen/just-try:latest
+        env:
+          KUBECONFIG: ${{ secrets.KUBECONFIG }}
+
+      - name: Rollout restart
+        run: kubectl rollout restart deployment/just-try-deployment
+        env:
+          KUBECONFIG: ${{ secrets.KUBECONFIG }}
